name: Build
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: PowerShell -File build.ps1
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            *.nupkg
